import type { Metadata } from "next";
import { lusitana } from "@/app/ui/font";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";



export const metadata: Metadata = {
  title: "My NextJS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`${lusitana} antialiased`}>
        {/* <Providers> */}
        <div className="flex flex-col min-h-screen">
          <ToastContainer position="bottom-right" autoClose={800} />
          {/* <Header /> */}

          {/* Thêm class flex-grow để đẩy footer xuống */}
          <main className="flex-grow">{children}</main>

          {/* <Footer /> */}
        </div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
